### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by leture** [Wrdlbrnft/BetterBarcodes#10]
Hello,

the project looks very promising and I would like to use it for an Android app of mine. What are the terms and conditions for incorporating the code into my own project? Is an explicit stating of one of the usual open source licenses just missing or do some special conditions apply here?

Best regards

**Comment by leture** [comment]
Hello, just a reminder here: this question has recently become urgent for me and I really would like to use this library but can not incorporate it without a clear knowledge about the licensing situation.

Best regards

**Comment by xaverkapeller** [comment]
Hi, sorry about the late response. I am no longer actively maintaining this library however it is licensed under MIT - so your are free to use it however you like, even for commercial purposes as long as you include proper attribution. I have committed the license to this repository here: a4cfc8d

**Comment by leture** [comment]
Thank you very much for your quick reaction!
